config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/shop',    :to => 'pages#shop'
  match '/videos', :to => 'pages#videos'
  match '/music',   :to => 'pages#music'
  match '/pictures',    :to => 'pages#pictures'
  match '/feeds', :to => 'pages#feeds'
  match '/press',   :to => 'pages#press'
  match '/events',    :to => 'pages#events'
  
  root :to => 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence => true,
					  :length   => { :maximum => 50 }
					
  validates :email, :presence => true,
					  :format   => { :with => email_regex },
					  :uniqueness => { :case_sensitive => false }
  
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
            
  before_save :encrypt_password
  
  def has_password?(submitted_password)
      encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
           
  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end          
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About"
  end
  
  def events
    @title = "Events"
  end
  
  def music
    @title = "Music"
  end
  
  def pictures
    @title = "Pictures"
  end
  
  def press
    @title = "Press"
  end
  
  def videos
    @title = "Videos"
  end
  
  def feeds
    @title = "Feeds"
  end
  
  def shop
    @title = "Shop"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @title = "Sign in"
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_back_or user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  
  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def new
    @user = User.new
    @title = "Sign up"
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      @title = "Sign up"
      @user.password = ""
      @user.password_confirmation = ""
      render 'new'      
    end
  end
  
  def edit
    @title = "Edit user"
  end
  
  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  
  private

   def authenticate
     deny_access unless signed_in?
   end
   
   def correct_user
     @user = User.find(params[:id])
     redirect_to(root_path) unless current_user?(@user)
   end
   
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
  	def logo
		logo = image_tag("title.png", :alt => "digaritmo")
 	 end
	 
	 def homeNav
		homeNav = image_tag("homeNav.png", :alt => "Home")
	 end

	 def press
		press = image_tag("press.png", :alt => "Press")
	 end
	 
	 def aboutNav
		aboutNav = image_tag("aboutNav.png", :alt => "About Us")
	 end
	 
	 def feeds
		feeds = image_tag("feeds.png", :alt => "Social Feeds")
	 end
	 
	 def events
		events = image_tag("events.png", :alt => "Live Events")
	 end
	 
	 def music
		music = image_tag("music.png", :alt => "Music")
	 end
	 
	 def videosNav
		videosNav = image_tag("videosNav.png", :alt => "Videos")
	 end
	 
	 def photos
		photos = image_tag("photos.png", :alt => "Photos")
	 end
	 
	 def shop
		shop = image_tag("shop.png", :alt => "Shop")
	 end
	 
	 def contact
		contact = image_tag("contact.png", :alt => "Contact Us")
	 end
	 
	 def welcome
		welcome = image_tag("welcome.png", :alt => "Welcome!")
	 end
	 
	 def pressH
		pressH = image_tag("pressH.png", :alt => "Press")
	 end
	 
	 def aboutH
		aboutH = image_tag("aboutH.png", :alt => "About Us")
	 end
	 
	 def feedsH
		feedsH = image_tag("feedsH.png", :alt => "Social Feeds")
	 end
	
	 def eventsH
		eventsH = image_tag("eventsH.png", :alt => "Live Events")
	 end
	 
	 def musicH
		musicH = image_tag("musicH.png", :alt => "Music")
	 end
	 
	 def videosH
		videosH = image_tag("videosH.png", :alt => "Videos")
	 end
	 
	 def photosH
		photosH = image_tag("photosH.png", :alt => "Photos")
	 end
	 
	 def shopH
		shopH = image_tag("shopH.png", :alt => "Coming Soon!")
	 end
	 
	 def contactH
		contactH = image_tag("contactH.png", :alt => "Contact Us")
	 end
	 
	 def facebook
		facebook = image_tag("facebook.png", :alt => "facebook")
	 end
	 
	 def twitter
		twitter = image_tag("twitter.png", :alt => "Twitter")
	 end
	 
	 def myspace
		myspace = image_tag("myspace.png", :alt => "MySpace")
	 end
	 
	 def soundcloud
		soundcloud = image_tag("soundcloud.png", :alt => "=SoundCloud")
	 end
	 
	 def youtube
		youtube = image_tag("youtube.png", :alt => "YouTube")
	 end
	 
	 def reverb
		reverb = image_tag("reverb.png", :alt => "Reverb Nation")
	 end
	
	def title
		base_title = "digaritmo - Speak Rhythm | Official Website"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end	
	end
	
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
	cookies.permanent.signed[:remember_token] = [user.id, user.salt]
	self.current_user = user
  end
  
  def current_user=(user)
	@current_user = user
  end
  
  def current_user
	@current_user ||= user_from_remember_token
  end
  
  def signed_in?
	!current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  private

	def user_from_remember_token
	  User.authenticate_with_salt(*remember_token)
	end

	def remember_token
	  cookies.signed[:remember_token] || [nil, nil]
	end
  
  def store_location
    session[:return_to] = request.fullpath
  end

  def clear_return_to
    session[:return_to] = nil
  end
end

app/helpers/user_helper.rb
module UserHelper

 def gravatar_for(user, options = { :size => 50 })
	gravatar_image_tag(user.email.downcase, :alt => user.name,
											:class => 'gravatar',
											:gravatar => options)
  end
  
end

app/views/layouts/_footer.html.erb
<footer>
  <nav> 
  <ul>
   <a href="http://facebook.com/digaritmo"><%= facebook %></a>
   <a href="http://www.youtube.com/user/digaritmo"><%= youtube%></a>
   <a href="http://twitter.com/digaritmo"><%= twitter%></a>
   <a href="http://soundcloud.com/digaritmo"><%= soundcloud%></a>
   <a href="http://www.myspace.com/digaritmo"><%= myspace%></a>
   <a href="http://www.reverbnation.com/digaritmo"><%= reverb%></a>
   </ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>  
</header>
<nav>
  <ul>  
    <li><%= link_to homeNav, root_path %></li>      
    <li><%= link_to press, press_path %></li>  
    <li><%= link_to aboutNav, about_path %></li>       
    <li><%= link_to feeds, feeds_path %></li>    
    <li><%= link_to events, events_path %></li>   
    <li><%= link_to music, music_path %></li> 
    <li><%= link_to videosNav, videos_path %></li>   
    <li><%= link_to photos, pictures_path %></li>      
    <li><%= link_to shop, shop_path %></li>  
    <li><%= link_to contact, contact_path %></li>
  </ul>
</nav>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <link rel="digaritmo icon" href="../images/squarelogo.jpg"/>  
      
    <%= csrf_meta_tag %>     
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %> 
    
    <meta property="fb:page_id" content="177991115583456" />
    
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-23130479-1']);
      _gaq.push(['_trackPageview']);
    (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    </script>    
  </head>
  
  <body>
 
    <div class="container">
          
      <![if IE 9]>
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, :class => "flash #{key}") %>
        <% end %>       
        <%= yield %>             
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
      <![endif]>
      
      <!--[if lte IE 8]>
       Welcome to DigaRitmo guitar duo's website. <br>
       To view the website you need the latest version of Internet Explorer:<br>
       <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home">
       Download Internet Explorer 9.</a><br><br>
       Or you could use Google Chrome:<br>
       <a href="http://www.google.com/chrome/intl/en/make/download.html?brand=CHKZ">
       Download Google Chrome.</a><br>
      <![endif]--> 
            
    </div>    
  </body>
  
</html>

app/views/pages/about.html.erb
<h1><%=aboutH%></h1>
<p> 
 <b>Today</b>
 <br>
 <br>
  We are a fresh, unique and energetic duo from South Africa. We have a lot of upcoming 
  projects after being finalists at the Yamaha Young Talent Competition in 2010 and performing
  at the 2011 KKNK. This includes the debut album (<i>Awaken</i>) which we are currently working on. 
  We hope to release it in early 2012. 
  <br>
  <br>
  We are also performing in shows all accross South Africa in 2011. This includes the Grahams Town Music festival,
  <i>inniBos</i> Music Festival and many more. Our show includes original compositions,
  arrangements of popular music from artists like Rodrigo & Gabriela and Carlos Santana as well as
  music from the famous film scores - "Desperado" & "Once upon a time in Mexico". 
  <br>
  <br>
  
 <b>The Name</b>
 <br>
 <br>
  We originally performed as <i>The Hats</i>. We chose that name on the spur of the moment when we needed
  to put a name on the entry form for the 2010 Yamaha Young Talent competition. However we later found 
  out there was a UK based band who were also <i>The Hats</i> and they were releasing a cd.
  We then decided to change our name. We knew that it would have to be something original, something that
  described our music and something which would not have been used anywhere else. That was the birth of
  DigaRitmo. DigaRitmo can be loosely translated from Spanish to mean 'speak rhythm'. <br>
 <br> 
 <br>
 
 <b>The History</b>
 <br>
 <br>
   In October 2010 we decided at the last moment to enter the Yamaha Young Talent competition. 
   Then after getting to the finals in Johannesburg, playing the encore and getting so much positive
   vibe afterwards from the audience we decided to 'play for keeps.' Since then we have performed about 
   50 times including performances at the 2011 KKNK and venues such as the Dorpstreet theatre in Stellenbosch. 
</p>

app/views/pages/contact.html.erb
<h1><%=contactH%></h1>

<bc class="round">
<img src="../images/bsscard.png" 
height="397" width="750" />
</bc>

app/views/pages/events.html.erb
<h4><%=eventsH%></h4>

<poster>
<a href="https://www.facebook.com/event.php?eid=116571411762842" target="_blank">
DigaRitmo Live at 'Ou Meul Teater (Old Mill Theater)' in Paarl ! </a>
<a href="https://www.facebook.com/event.php?eid=203378493031813" target="_blank">
<img src="https://lh3.googleusercontent.com/-u_acufm7eYY/TfTZFpU0EcI/AAAAAAAAAXM/XSe-4xaDyvk/s800/Die%252520Ou%252520Meul%252520Poster.jpg" 
height="800" width="623" alt="DigaRitmo Live at 'Ou Meul Teater (Old Mill Theater)' in Paarl !" />
</a>
</poster>

<br><br><br>

<poster>
<a href="https://www.facebook.com/event.php?eid=116530461768341" target="_blank">
DigaRitmo Live at 'Aan De Braak Teater' in Stellenbosch!
<a href="https://www.facebook.com/event.php?eid=203378493031813" target="_blank">
<img src="https://lh3.googleusercontent.com/-u_acufm7eYY/TfTZFpU0EcI/AAAAAAAAAXM/XSe-4xaDyvk/s800/Die%252520Ou%252520Meul%252520Poster.jpg" 
height="800" width="623" alt="DigaRitmo Live at 'Aan De Braak Teater' in Stellenbosch!" />
</a>
</poster>

<br><br><br>

<poster>
<a href="https://www.facebook.com/event.php?eid=203378493031813" target="_blank">
DigaRitmo Live at "The Ladle" in Greyton!
<a href="https://www.facebook.com/event.php?eid=203378493031813" target="_blank">
<img src="https://lh6.googleusercontent.com/-fS8BbkAwD2Q/TeUwS18d78I/AAAAAAAAAJo/xl4pc2gXKiw/s800/posterl.jpg" 
height="800" width="623" alt="DigaRitmo Live at "The Ladle" in Greyton!" />
</a>
</poster>

app/views/pages/feeds.html.erb
<h3><%=feedsH%></h3>

<fb>
	<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#xfbml=1">
	</script><fb:like-box href="http://www.facebook.com/digaritmo" width="350" 
	show_faces="true" stream="true" header="true"></fb:like-box>
</fb>	

<tw>
<script src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'profile',
  rpp: 20,
  interval: 6000,
  width: 350,
  height: 500,
  theme: {
	shell: {
	  background: '#0072bc',
	  color: '#ffffff'
	},
	tweets: {
	  background: '#ffffff',
	  color: '#303030',
	  links: '#0072bc'
	}
  },
  features: {
	scrollbar: true,
	loop: false,
	live: false,
	hashtags: true,
	timestamp: true,
	avatars: true,
	behavior: 'all'
  }
}).render().setUser('digaritmo').start();
</script>
</tw>

<br clear="all" />

app/views/pages/home.html.erb
<h4><%=welcome%></h4>

<squarelogo>
<img src="../images/squarelogo.jpg" 
height="128" width="128" />
</squarelogo>

<roundlogo>
<img src="../images/roundlogo.jpg" 
height="128" width="128" />
</roundlogo>

<smrCntr>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
Welcome to DigaRitmo guitar duo's website.  <br>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
We hope you enjoy the content ! <br><br>

</smrCntr>

<mail>
<img style="visibility:hidden;width:0px;height:0px;" border=0 width=0 height=0 
src="http://c.gigcount.com/wildfire/IMP/CXNID=2000002.11NXC/bT*xJmx*PTEzMDcwNTU4OTMyMjYmcHQ9MTMwNzA1NTg5NTM1OSZwPTI3MDgxJmQ9cHJvX2ZhbmNvbGxlY3Rvcl9maXJzdF9nZW4m/Zz*xJm9mPTA=.gif" />
<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="250" height="101"><param name="movie" 
value="http://cache.reverbnation.com/widgets/swf/44/pro_widget.swf?id=artist_1502427&posted_by=&skin_id=PWFS5008&font_color=333333&street_team=false"></param>
<param name="allowscriptaccess" value="always"></param><param name="allowNetworking" value="all"></param><param name="allowfullscreen" value="true"></param>
<param name="wmode" value="transparent"></param><param name="quality" value="best"></param><embed src="http://cache.reverbnation.com/widgets/swf/44/pro_widget.swf?id=artist_1502427&posted_by=&skin_id=PWFS5008&font_color=333333&street_team=false" 
type="application/x-shockwave-flash" allowscriptaccess="always" allowNetworking="all" allowfullscreen="true" wmode="transparent" quality="best" width="250" height="118"></embed></object><br/>
<img style="visibility:hidden;width:0px;height:0px;" border=0 width=0 height=0 src="http://www.reverbnation.com/widgets/trk/44/artist_1502427//t.gif" />
</mail>

<smrCntr2>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
You should find what you're looking for here, <br>
if you don't please leave a comment and we'll find it for you. <br><br> &nbsp
</smrCntr2>


<!--[if IE]><comments2>
<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#xfbml=1">
</script><fb:comments href="digaritmo.com" num_posts="1" width="440" 
colorscheme="light"></fb:comments>
</comments2><![endif]-->

<![if !IE]><comments>
<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#xfbml=1">
</script><fb:comments href="digaritmo.com" num_posts="1" width="440" 
colorscheme="light"></fb:comments>
</comments><![endif]>

<br clear="all" />

app/views/pages/music.html.erb
<h2><%=musicH%></h2>

<sc>
	These are some home studio recordings of our songs:
	<object height="225" width="100%"> <param name="movie" value="http://player.soundcloud.com/player.swf?url=http%3A%2F%2Fapi.soundcloud.com%2Fusers%2F4289649&amp;
	show_comments=true&amp;auto_play=true&amp;show_playcount=true&amp;show_artwork=true&amp;color=0072bc"></param> <param name="allowscriptaccess" value="always">
	</param> <embed allowscriptaccess="always" height="225" src="http://player.soundcloud.com/player.swf?url=http%3A%2F%2Fapi.soundcloud.com%2Fusers%2F4289649&amp;
	show_comments=true&amp;auto_play=true&amp;show_playcount=true&amp;show_artwork=true&amp;color=0072bc" type="application/x-shockwave-flash" width="100%"></embed> 
	</object>   <span><a href="http://soundcloud.com/digaritmo">Latest tracks by digaritmo</a></span>
	<br>&nbsp&nbspWe give you free downloads please give us a like and share on facebook:
	<br>&nbsp
</sc>

<like class="white">
<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#appId=231372543543918&amp;xfbml=1">
</script><fb:like href="facebook.com/digaritmo" send="true" 
width="450" show_faces="true" colorscheme="light" font="verdana"></fb:like>

<br clear="all" />

app/views/pages/pictures.html.erb
<h2><%=photosH%></h2>

<smr>
Walking around in Stellenbosch:<br><br>&nbsp
</smr>
<ph>
 <embed type="application/x-shockwave-flash"
 src="https://picasaweb.google.com/s/c/bin/slideshow.swf" 
 width="750" height="500" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2Fdigaritmo%2Falbumid%2F5611548676464110433%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCPnM2_mn35PZLA%26hl%3Den_US" 
 pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
</ph>

<smr><br><br>
Yamaha Young Talent Finals:<br><br>&nbsp
</smr>
<ph>
 <embed type="application/x-shockwave-flash" src="https://picasaweb.google.com/s/c/bin/slideshow.swf" 
 width="750" height="500" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F110544630515312323741%2Falbumid%2F5611547776704596753%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCIuArfDE3o22Rg%26hl%3Den_US" 
 pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
</ph>

<smr><br><br>
KKNK 2011:<br><br>&nbsp
</smr>
<ph>
<embed type="application/x-shockwave-flash" src="https://picasaweb.google.com/s/c/bin/slideshow.swf" 
width="750" height="500" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2Fdigaritmo%2Falbumid%2F5611551750361917009%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCN2at4flxvzn0AE%26hl%3Den_US" 
pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
</ph>

<smr><br><br>
Chatting with Corne from CH2:<br><br>&nbsp
</smr>
<ph>
 <embed type="application/x-shockwave-flash" src="https://picasaweb.google.com/s/c/bin/slideshow.swf" 
 width="750" height="500" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2Fdigaritmo%2Falbumid%2F5611549921912064465%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCKXIt_7Iv7fMrQE%26hl%3Den_US" 
 pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
</ph>

app/views/pages/press.html.erb
<h1><%=pressH%></h1>
<p> 
 <b>Dorpstraat Theatre</b>
 <br>
 <br>
	 &nbsp&nbsp"According to a very old man, the first account of melodic lyricism was around the time of the big bang when the expansion of the universe 
	 &nbsp&nbspcreated a sound so loud and romantic, it had to be considered musical. Experience a sound explosion of similar proportions with a ticket to 
	 &nbsp&nbspDigaritmo at the Dorpstraat Theatre."
 <br>
 <br>	
	&nbsp&nbsp- Dorpstraat Theatre
	<br>&nbsp&nbsp&nbspSummerhill Wine Farm, Adam Tas Street , 7599 Stellenbosch
</p>

app/views/pages/shop.html.erb
<h3><%=shopH%></h3><smr>Posters, T-Shirts, Stickers...</smr>

app/views/pages/videos.html.erb
<h2><%=videosH%></h2>

<smr>
DigaRitmo performing Awaken at the KKNK:<br><br>&nbsp
</smr>
<yt>
<iframe width="750" height="457" 
src="http://www.youtube.com/embed/8yGtX6fupqI" frameborder="0" 
allowfullscreen></iframe>
</yt>

<smr>
<br><br>
DigaRitmo performing Cancion del Mariachi at the KKNK:<br><br>&nbsp
</smr>
<yt>
<iframe width="750" height="457" 
src="http://www.youtube.com/embed/aUIheiHqb5M" frameborder="0" 
allowfullscreen></iframe>
</yt>

<smr>
<br><br>
DigaRitmo at La Dolce Vita after the KKNK:<br><br>&nbsp
</smr>
<yt>
<iframe width="750" height="457" 
src="http://www.youtube.com/embed/P6gMX_3rSh4" frameborder="0" 
allowfullscreen></iframe>
</yt>

<smr>
<br><br>
DigaRitmo performing Gypsy Dusk at the KKNK:<br><br>&nbsp
</smr>
<yt>
<iframe width="750" height="457" 
src="http://www.youtube.com/embed/-XNwCOXxX40" frameborder="0" 
allowfullscreen></iframe>
</yt>

<smr>
<br><br>
DigaRitmo performing Shameless Pain at the KKNK:<br><br>&nbsp
</smr>
<yt>
<iframe width="750" height="457" 
src="http://www.youtube.com/embed/NLqscb-m5IU" frameborder="0" 
allowfullscreen></iframe>
</yt>

<smr>
<br><br>
DigaRitmo performing Midday Stars at the KKNK:<br><br>&nbsp
</smr>
<yt>
<iframe width="750" height="457" 
src="http://www.youtube.com/embed/Fmh2QaCIYkE" frameborder="0" 
allowfullscreen></iframe>
</yt>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">  <tr>	<td class="main">	  <h1>		<%= gravatar_for @user %>		<%= @user.name %>	  </h1>	</td>	<td class="sidebar round">	  <strong>Name</strong> <%= @user.name %><br />	  <strong>URL</strong>  <%= link_to user_path(@user), @user %>	</td>  </tr></table>